config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end




   devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'

  }

    devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
  }

  scope module: :public do
      root to: 'homes#top'
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts do
      collection do
        get 'search'
      end
      resource :favorite, only: [ :create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

  end

  namespace :admin do
    resources :users,     only: [:index, :show, :edit, :update, :destroy]
    resources :posts do
      resources :comments
    end
    get '/search' => 'searches#search'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  belongs_to :user

  validates :name, presence: true
  validates :introduction, presence: true


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  GUEST_EMAIL = "guest@example.com"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :encrypted_password, presence: true


  enum role: { user: 0, admin: 10, customer: 20, }

  def self.guest
    find_or_create_by!(email: GUEST_EMAIL) do |user|
      user.name = "ゲスト"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # def get_profile_image(width, height)
  #   unless profile_image.attached?
  #     file_path = Rails.root.join("app/assets/images/no_image.jpg")
  #     profile_image.attach(io: File.open(file_path), filename: "no_image.jpg", content_type: "image/jpeg")
  #   end

  #   profile_image.variant(resize_to_limit: [width, height]).processed
  #   # profile_image.variant(resize_to_limit: [100, 100]).processed
  # end

  def is_guest?
    email == GUEST_EMAIL
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_post_path(params[:post_id])
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:show,:new]
  before_action :set_q, only: [:index]

  def index
    @posts = Post.page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:name, :introduction, :image)
  end

  def set_q
    @q = Post.ransack(params[:q])
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @user = User.all
  end

  def destroy
    if @user = User.find(params[:id]).destroy
      redirect_to root_path, notice: "退会しました"
    else
      redirect_to "/", notice: "エラー"
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users/favorites_helper.rb
module Users::FavoritesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/posts/index.html.erb
<h1>新規投稿一覧</h1>

<div class="d-flex flex-row-reverse bd-highlight">
  <div class="p-2 bd-highlight">
    <%= search_form_for @q, url:  search_posts_path do |f| %>
      <%= f.label :name_cont, 'キーワード検索' %>
      <%= f.search_field :name_cont %>
      <br>
      <%= f.submit '検索', class:"btn btn-primary py-0" %>
    <% end %>
  </div>
    <div class="p-2 bd-highlight">
      <%= form_tag admin_posts_path, method: :get, class: 'boards__searchForm' do %>
        <%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
          {
            prompt: 'タグで絞り込み検索',
            onchange: 'submit(this.form);'
          }%>
      <% end %>
    </div>
</div>

<div class="sample">
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">本文</th>
      <th scope="col">投稿写真</th>
      <th scope="col">タグ</th>
    </tr>
  </thead>
<tbody>
<% @posts.each do |post| %>
  <tr>
  <td><%= link_to post.name, admin_post_path(post.id) %></td>
  <td><%= post.introduction %></td>
  <td>
    <% if post.image.attached? %>
      <%= image_tag post.image, size: "100x100" %>
    <% else %>
      <%= image_tag 'no_image', size: "100x100" %>
    <% end %></td>
  <td>
    <% post.tags.each do |tag| %>
      <%= tag.name %>
    <% end %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/admin/posts/show.html.erb
<div class="main_center">
  <h2>管理者用投稿詳細ページ</h2>
    <div class="sample">
      <h3>タイトル</h3>
      <p><%= @post.name %></p>
    </div>
    <div class="sample">
      <h3>本文</h3>
      <p><%= @post.introduction %></p>
    </div>
    <div class="sample">
      <h3>投稿写真</h3>
      <% if @post.image.attached? %>
        <%= image_tag @post.image, size: "100x100" %>
      <% else %>
        <%= image_tag 'no_image', size: "100x100" %>
      <% end %>
    </div>
    <div class="sample">
      <h3>タグ</h3>
      <% @post.tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
 </div>

<%= link_to "投稿の削除", admin_post_path(@post.id), class:"btn btn-danger py-0", method: :delete, "data-confirm" => "本当に削除しますか？" %>

<% if admin_signed_in? %>
  ♥<%= @post.favorites.count %> いいね
<% elsif user_signed_in? %>
  <% if @post.favorited_by?(current_user) %>
    <p>
      <%= link_to post_favorite_path(@post), method: :delete do %>
        ♥<%= @post.favorites.count %> いいね
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to post_favorite_path(@post), method: :post do %>
        ♡<%= @post.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
<% end %>

  <div>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">投稿者</th>
            <th scope="col">コメント日時</th>
            <th scope="col">コメント</th>
            <th scope="col"></th></th>
          </tr>
        </thead>
      <tbody>
        <p>コメント件数：<%= @post.comments.count %></p>
        <% @post.comments.each do |comment| %>
        <tr>
          <td><%= comment.user.name %></td>
          <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= comment.comment %></td>
          <td>
              <%= link_to "削除", admin_post_comment_path(comment.post, comment), class:"btn btn-danger py-0", method: :delete, "data-confirm" => "本当に削除しますか？" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>