config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end




   devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'

  }

    devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
  }

  scope module: :public do
      root to: 'homes#top'
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts do
      collection do
        get 'search'
      end
      resource :favorite, only: [ :create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

  end

  namespace :admin do
    resources :users,     only: [:index, :show, :edit, :update, :destroy]
    resources :posts do
      resources :comments
    end
    get '/search' => 'searches#search'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  belongs_to :user

  validates :name, presence: true
  validates :introduction, presence: true


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  GUEST_EMAIL = "guest@example.com"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :encrypted_password, presence: true


  enum role: { user: 0, admin: 10, customer: 20, }

  def self.guest
    find_or_create_by!(email: GUEST_EMAIL) do |user|
      user.name = "ゲスト"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # def get_profile_image(width, height)
  #   unless profile_image.attached?
  #     file_path = Rails.root.join("app/assets/images/no_image.jpg")
  #     profile_image.attach(io: File.open(file_path), filename: "no_image.jpg", content_type: "image/jpeg")
  #   end

  #   profile_image.variant(resize_to_limit: [width, height]).processed
  #   # profile_image.variant(resize_to_limit: [100, 100]).processed
  # end

  def is_guest?
    email == GUEST_EMAIL
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:show,:new]
  before_action :set_q, only: [:index]

  def index
    @posts = Post.page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:name, :introduction, :image)
  end

  def set_q
    @q = Post.ransack(params[:q])
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @user = User.all
  end

  def destroy
    if @user = User.find(params[:id]).destroy
      redirect_to root_path, notice: "退会しました"
    else
      redirect_to "/", notice: "エラー"
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users/favorites_helper.rb
module Users::FavoritesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oldcarmag</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light px-0 bg-light">
        <div class="container">
        <%= link_to  root_path, class:"my-0" do %>
        <% end %>
        <h6 class="my-auto offset-md-1">
          <% if current_user %>
            <i class="h4 fas fa-user-check"></i>ようこそ、<%= current_user.name %>様！
          <% elsif current_admin %>
            <i class="h4 fas fa-key"></i>管理者としてログインしています！
          <% else %>

          <% end %>
        </h6>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarcontent" aria-controls="navbarcontent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarcontent">
          <ul class="navbar-nav ml-auto">
            <% if current_user %>
              <li class="nav-item">
                <%= link_to "マイページ", user_path(current_user.id), class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", posts_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規投稿", new_post_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, class:"nav-link", method: :delete %>
              </li>

            <% elsif current_admin %>
              <li class="nav-item">
                <%= link_to "会員リスト", admin_users_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", admin_posts_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, class:"nav-link", method: :delete %>
              </li>

            <% else %>
              <li class="nav-item">
                <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "管理者ログイン", new_admin_session_path, class:"nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <% flash.each do |key, msg| %>
        <p><%= msg %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>